apiVersion: v1
kind: Service
metadata:
  name: threecx-call-worker
  namespace: threecx-worker
  labels:
    app: threecx-call-worker
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: threecx-call-worker
